### ISSUE TITLE
Support for attaching VPCs to existing transit gateway (across accounts)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-transit-gateway#158]
### Description

Add support for attaching VPC(s) for another account in an existing transit gateway.
Note that there is a step where the connection must be accepted from the target account. Such support to accept connection does not appear to exist in the ibm terraform provider as of now - so there may be the need to work with the provider team to add such (https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4347) - and potentially add a call via the restapi provider to the https://cloud.ibm.com/apidocs/transit-gateway#create-transit-gateway-connection-actions as a stop gap solution.

### New or affected modules

- [terraform-ibm-transit-gateway](https://github.com/terraform-ibm-modules/terraform-ibm-transit-gateway)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vbontempi** [comment]
opened PR https://github.com/terraform-ibm-modules/terraform-ibm-transit-gateway/pull/249

**Comment by vbontempi** [comment]
As per comment at https://github.com/terraform-ibm-modules/terraform-ibm-transit-gateway/pull/249#pullrequestreview-1365307692 adding support for existing transit gateway with this task

**Comment by vburckhardt** [comment]
This is complete - closing.
