### ISSUE TITLE
Bump delete timeout on ibm_tg_gateway

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-transit-gateway#263]
### Description

As per service team: Usual deletion target is in the 10-20 minute range... in this case there was a dependent service that did some maintenance which caused delete delays in a handful of regions and this customer happened to hit most of them"

Perhaps set the delete timeout on the resource to 45 minutes as a start

**Comment by Khuzaima05** [comment]
PR merged
